version: '0.2'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - 80:80
    volumes:
      - C:/upload:/usr/share/nginx/html:ro           # HTML 파일 마운트
    restart: always

  upload_container:
    image: eggzuxi/uploadapi:latest

    container_name: uploadapi_container
    ports:
      - 8080:8080
    environment:
      - com.example.upload.productpath=/app/upload/product
      - com.example.upload.qrimagepath=/app/upload/qrcode
      - spring.multipart.location=/app/upload
      - spring.datasource.url=jdbc:mariadb://10.10.10.92:13306/team4db
    networks:
      - uploadnet
    volumes:
      - C:/upload/:/app/upload


networks:
  uploadnet: {}