spring:
  application:
    name: demo6
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/team4db
#    url: jdbc:mariadb://10.10.10.217:13306/tripwhiz
    username: team4dbuser
    password: team4dbuser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: C:\\upload
      enabled: true

com:
  example:
    accessTime: 60
    refreshTime: 10080
    alwaysNew: true
    upload:
      path: C:\\upload
#      path: /c/upload/attach  # image upload path
      qrpath: qrimages
    user:
      api:
        url: http://localhost:8081  # User API의 URL

logging:
  level:
    org.springframework.security.web: TRACE
    springframework:
      security: trace
      logging:
        level:
          org:
            springframework:
              security=DEBUG:

  spring:
    mvc:
      throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false





