spring:
  application:
    name: demo6

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/team4db
    username: team4dbuser
    password: team4dbuser



