spring:
  application:
    name: demo6
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://team4db.cv9k7s92hqrr.ap-northeast-2.rds.amazonaws.com:13306/team4db
    url: jdbc:mariadb://localhost:13306/team4db
    username: team4dbuser
    password: team4dbuser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: /app/upload  # 컨테이너 내부 업로드 경로와 일치
      enabled: true

com:
  example:
    accessTime: 60
    refreshTime: 10080
    alwaysNew: true
    uploadBasic: C:\\upload
    upload:
      productpath: product   # 상품 이미지 저장 경로
      qrcodepath: qrcode   # QR 코드 이미지 저장 경로
      storagepath: storage
      movingpath: moving
    user:
      api:
        url: http://localhost:8081

firebase:
  config:
    file: /app/firebase/firebase-config.json # Firebase JSON 파일의 위치

logging:
  level:
    org.springframework.security.web: TRACE
    com.example.demo: TRACE

  spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  port: 8082
